---
title: "Evaluating classifiers on pathogens"
output: html_notebook
author: "Patrick Schratz, FSU Jena"
---

This report evaluates the classifiers Random Forest (RF), Support Vector Machine (SVM) and Extreme Gradient Boosting (xgboost) on four different pathogens:

- _Armillaria mellea_
- _Diplodia sapinea_
- _Fusarium mellea_
- _Heterobasidion mellea_

```{r setup, include=FALSE}
loadd(bm_glm, bm_rf, bm_svm, bm_kknn)
drake::loadd(bm_glm, bm_rf, bm_svm, bm_kknn)
knitr::opts_chunk$set(eval = FALSE)
```

# Load benchmark results

```{r benchmark-eval-1}
bmr_all = mergebmResults(list(bm_rf, bm_svm, bm_xgboost,
                              bm_kknn, bm_glm
))
```

# Print benchmark results

```{r benchmark-eval-2}
getBMRAggrPerformances(bmr_all, as.df = TRUE) %>%
  arrange(task.id, desc(brier.test.mean))
```

# Visualize

```{r benchmark-eval-3}
plt = plotBMRBoxplots(bmr_all, measure = brier, pretty.names = FALSE, 
  order.lrn = getBMRLearnerIds(bmr_all)) +
  # aes(color = learner.id) +
  # scale_color_viridis_d() +
  theme(strip.text.x = element_text(size = 8)) + 
  theme_pubr()

levels(plt$data$task.id) = c("Armillaria", "Diplodia", "Fusarium", "Heterobasidion")
levels(plt$data$learner.id) = c("SVM", "RF", "GLM")

plt + ylab("Performance")
```

## Aggregated performances

```{r benchmark-eval-4}
plt2 = plotBMRSummary(bmr_all) + 
  theme_pubr()

levels(plt2$data$task.id) = c("Armillaria", "Diplodia", "Fusarium", "Heterobasidion")
levels(plt2$data$learner.id) = c("SVM", "RF", "GLM")

plt2
```

## Calculating and visualizing ranks

```{r benchmark-eval-5}
m = convertBMRToRankMatrix(bmr_all, brier)
as_tibble(m)
```

```{r benchmark-eval-6}
plt3 = plotBMRRanksAsBarChart(bmr_all, pos = "tile", order.lrn = getBMRLearnerIds(bmr_all)) +
  theme_pubr()

levels(plt3$data$task.id) = c("Armillaria", "Diplodia", "Fusarium", "Heterobasidion")
levels(plt3$data$learner.id) = c("SVM", "RF", "GLM")

plt3
```

