---
title: "Visualization of partitions"
output: html_document
author: "Patrick Schratz, FSU Jena"
---

Visualization of optimization paths for the first five folds.

```{r setup}
knitr::opts_knit$set(base.dir = 'analysis/rmd/')
knitr::opts_chunk$set(fig.retina=3, fig.align = 'center',
                      out.width = "100%")
```

# Resampling strategies {.tabset .tabset-fade}

## Spatial/Spatial

```{r}
loadd(bm_sp_sp_diplodia)

opt_path_diplodia_sp_sp = vis_opt_path(bm_sp_sp_diplodia$results$diplodia)
```

### GAM

```{r opt-path-gam-sp-sp, fig.width = 9.93, fig.height = 4.13, fig.path="../../analysis/paper/submission/3/appendices/", dev = c("png")}
opt_path_diplodia_sp_sp[[1]]
```

### KKNN

```{r opt-path-knn-sp-sp, fig.width = 9.93, fig.height = 4.13, fig.path="../../analysis/paper/submission/3/appendices/", dev = c("png")}
opt_path_diplodia_sp_sp[[2]]
```

### RF 

```{r opt-path-rf-sp-sp, fig.width = 9.93, fig.height = 4.13, fig.path="../../analysis/paper/submission/3/appendices/", dev = c("png")}
opt_path_diplodia_sp_sp[[3]]
```

### SVM 

```{r opt-path-svm-sp-sp, fig.width = 9.93, fig.height = 4.13, fig.path="../../analysis/paper/submission/3/appendices/", dev = c("png")}
opt_path_diplodia_sp_sp[[4]]
```

### BRT 

```{r opt-path-brt-sp-sp, fig.width = 9.93, fig.height = 4.13, fig.path="../../analysis/paper/submission/3/appendices/", dev = c("png")}
opt_path_diplodia_sp_sp[[5]]
```

## Spatial/Non-Spatial

```{r}
loadd(bm_sp_nsp_diplodia)

opt_path_diplodia_sp_nsp = vis_opt_path(bm_sp_nsp_diplodia$results$diplodia)
```

### GAM

```{r opt-path-gam-sp-nsp, fig.width = 9.93, fig.height = 4.13, fig.path="../../analysis/paper/submission/3/appendices/", dev = c("png")}
opt_path_diplodia_sp_nsp[[1]]
```

### KKNN

```{r opt-path-knn-sp-nsp, fig.width = 9.93, fig.height = 4.13, fig.path="../../analysis/paper/submission/3/appendices/", dev = c("png")}
opt_path_diplodia_sp_nsp[[2]]
```

### RF 

```{r opt-path-rf-sp-nsp, fig.width = 9.93, fig.height = 4.13, fig.path="../../analysis/paper/submission/3/appendices/", dev = c("png")}
opt_path_diplodia_sp_nsp[[3]]
```

### SVM 

```{r opt-path-svm-sp-nsp, fig.width = 9.93, fig.height = 4.13, fig.path="../../analysis/paper/submission/3/appendices/", dev = c("png")}
opt_path_diplodia_sp_nsp[[4]]
```

### BRT 

```{r opt-path-brt-sp-nsp, fig.width = 9.93, fig.height = 4.13, fig.path="../../analysis/paper/submission/3/appendices/", dev = c("png")}
opt_path_diplodia_sp_nsp[[5]]
```

## Non-Spatial/Non-Spatial

```{r}
loadd(bm_nsp_nsp_diplodia)

opt_path_diplodia_nsp_nsp = vis_opt_path(bm_nsp_nsp_diplodia$results$diplodia)
```

### GAM

```{r opt-path-gam-nsp-nsp, fig.width = 9.93, fig.height = 4.13, fig.path="../../analysis/paper/submission/3/appendices/", dev = c("png")}
opt_path_diplodia_nsp_nsp[[1]]
```

### KKNN

```{r opt-path-knn-nsp-nsp, fig.width = 9.93, fig.height = 4.13, fig.path="../../analysis/paper/submission/3/appendices/", dev = c("png")}
opt_path_diplodia_nsp_nsp[[2]]
```

### RF 

```{r opt-path-rf-nsp-nsp, fig.width = 9.93, fig.height = 4.13, fig.path="../../analysis/paper/submission/3/appendices/", dev = c("png")}
opt_path_diplodia_nsp_nsp[[3]]
```

### SVM 

```{r opt-path-svm-nsp-nsp, fig.width = 9.93, fig.height = 4.13, fig.path="../../analysis/paper/submission/3/appendices/", dev = c("png")}
opt_path_diplodia_nsp_nsp[[4]]
```

### BRT 

```{r opt-path-brt-nsp-nsp, fig.width = 9.93, fig.height = 4.13, fig.path="../../analysis/paper/submission/3/appendices/", dev = c("png")}
opt_path_diplodia_nsp_nsp[[5]]
```

# Comparison RF sp vs nsp

```{r opt-paths-RF-sp-vs-nsp, fig.width = 12, fig.path="../../analysis/paper/submission/3/latex-source-files/", dev = c("png", "pdf")}
# remove title, we use cowplot labels
opt_path_diplodia_sp_sp[[3]] = opt_path_diplodia_sp_sp[[3]] + ggtitle("")
opt_path_diplodia_sp_nsp[[3]] = opt_path_diplodia_sp_nsp[[3]] + ggtitle("")

plot_grid(opt_path_diplodia_sp_sp[[3]], opt_path_diplodia_sp_nsp[[3]],
          labels = c("RF (sp/sp)", "RF (sp/nsp)"),
          ncol = 1, nrow = 2
)
```

