---
title: "Exploratory data analysis"
author: "Marc Becker"
output:
  html_notebook:
    code_folding: none
    fig_width: 10
    highlight: haddock
    number_sections: yes
    toc: yes
---

```{r}
library(tibble)
library(dplyr)
```

```{r}
readRDS('/data/marc/mod/survey_data/heterobasi_data.rda') %>% as_tibble() -> heterobasi_data
readRDS('/data/marc/mod/survey_data/armillaria_data.rda') %>% as_tibble() -> armillaria_data
```

# Spine plots

```{r}
spineplot(formula = heterobasi ~ elevation, data = heterobasi_data)
spineplot(formula = heterobasi ~ slope, data = heterobasi_data)
spineplot(formula = heterobasi ~ soil, data = heterobasi_data)
spineplot(formula = heterobasi ~ ph, data = heterobasi_data)
spineplot(formula = heterobasi ~ lithology, data = heterobasi_data)
spineplot(formula = heterobasi ~ temperature, data = heterobasi_data)
spineplot(formula = heterobasi ~ pisr, data = heterobasi_data)
spineplot(formula = heterobasi ~ precipitation, data = heterobasi_data)
spineplot(formula = heterobasi ~ hail_probability, data = heterobasi_data)
```


```{r}
spineplot(formula = armillaria ~ elevation, data = armillaria_data)
spineplot(formula = armillaria ~ slope, data = armillaria_data)
spineplot(formula = armillaria ~ soil, data = armillaria_data)
spineplot(formula = armillaria ~ ph, data = armillaria_data)
spineplot(formula = armillaria ~ lithology, data = armillaria_data)
spineplot(formula = armillaria ~ temperature, data = armillaria_data)
spineplot(formula = armillaria ~ pisr, data = armillaria_data)
spineplot(formula = armillaria ~ precipitation, data = armillaria_data)
spineplot(formula = armillaria ~ hail_probability, data = armillaria_data)
```

