---
title: "Visualization of optimization paths during hyperparameter tuning"
output: workflowr::wflow_html
author: "Patrick Schratz, FSU Jena"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.retina = 3, 
                      fig.align = 'center',
                      fig.width = 9.93, 
                      fig.height = 4.13,
                      out.width = "100%",
                      echo = FALSE
                      )

source(here::here("code/99-packages.R"))
sourceDirectory("R")

loadd(bm_sp_sp_diplodia, bm_sp_nsp_diplodia, bm_nsp_nsp_diplodia)
```

Visualization of optimization paths for the first five folds.

# Resampling strategies {.tabset .tabset-fade}

## Spatial/Spatial

```{r}
opt_path_diplodia_sp_sp = suppressWarnings(suppressMessages(vis_opt_path(bm_sp_sp_diplodia$results$diplodia)))
```

### GAM

```{r opt-path-gam-sp-sp, dev = c("png")}
print(opt_path_diplodia_sp_sp[[1]])
```

### KKNN

```{r opt-path-knn-sp-sp, dev = c("png")}
opt_path_diplodia_sp_sp[[2]]
```

### RF 

```{r opt-path-rf-sp-sp, dev = c("png")}
opt_path_diplodia_sp_sp[[3]]
```

### SVM 

```{r opt-path-svm-sp-sp, dev = c("png")}
opt_path_diplodia_sp_sp[[4]]
```

### BRT 

```{r opt-path-brt-sp-sp, dev = c("png")}
opt_path_diplodia_sp_sp[[5]]
```

## Spatial/Non-Spatial

```{r}
opt_path_diplodia_sp_nsp = suppressWarnings(suppressMessages(vis_opt_path(bm_sp_nsp_diplodia$results$diplodia)))
```

### GAM

```{r opt-path-gam-sp-nsp, dev = c("png")}
opt_path_diplodia_sp_nsp[[1]]
```

### KKNN

```{r opt-path-knn-sp-nsp, dev = c("png")}
opt_path_diplodia_sp_nsp[[2]]
```

### RF 

```{r opt-path-rf-sp-nsp, dev = c("png")}
opt_path_diplodia_sp_nsp[[3]]
```

### SVM 

```{r opt-path-svm-sp-nsp, dev = c("png")}
opt_path_diplodia_sp_nsp[[4]]
```

### BRT 

```{r opt-path-brt-sp-nsp, dev = c("png")}
opt_path_diplodia_sp_nsp[[5]]
```

## Non-Spatial/Non-Spatial

```{r}
opt_path_diplodia_nsp_nsp = suppressWarnings(suppressMessages(vis_opt_path(bm_nsp_nsp_diplodia$results$diplodia)))
```

### GAM

```{r opt-path-gam-nsp-nsp, dev = c("png")}
opt_path_diplodia_nsp_nsp[[1]]
```

### KKNN

```{r opt-path-knn-nsp-nsp, dev = c("png")}
opt_path_diplodia_nsp_nsp[[2]]
```

### RF 

```{r opt-path-rf-nsp-nsp, dev = c("png")}
opt_path_diplodia_nsp_nsp[[3]]
```

### SVM 

```{r opt-path-svm-nsp-nsp, dev = c("png")}
opt_path_diplodia_nsp_nsp[[4]]
```

### BRT 

```{r opt-path-brt-nsp-nsp, dev = c("png")}
opt_path_diplodia_nsp_nsp[[5]]
```

# Comparison RF sp vs nsp

```{r opt-paths-RF-sp-vs-nsp, fig.width = 12, fig.height = 10, dev = c("png", "pdf")}
# remove title, we use cowplot labels
opt_path_diplodia_sp_sp[[3]] = opt_path_diplodia_sp_sp[[3]] + ggtitle("")
opt_path_diplodia_sp_nsp[[3]] = opt_path_diplodia_sp_nsp[[3]] + ggtitle("")

plot_grid(opt_path_diplodia_sp_sp[[3]], opt_path_diplodia_sp_nsp[[3]],
          labels = c("RF (sp/sp)", "RF (sp/nsp)"),
          ncol = 1, nrow = 2
)
```

```{r echo = FALSE}
files_in = list.files(here("docs/figure/figure/vis-opt-paths.Rmd/"), 
                      pattern = "opt-paths", 
                      full.names = TRUE)
file_copy(files_in,
          rep(here("code/07-paper/submission/3/appendices/"), 
              length(files_in)),
          overwrite = TRUE)
```

```{r echo = FALSE}
file_move(list.files(here("code/07-paper/submission/3/appendices"), 
                     pattern = "opt-paths-RF-sp-vs-nsp", 
                     full.names = TRUE),
          here("code/07-paper/submission/3/latex-source-files/"))
```
