---
title: "Visualization of partitions"
output: workflowr::wflow_html
author: "Patrick Schratz, FSU Jena"
---

Visualization of optimization paths for the first five folds.

```{r setup}
knitr::opts_knit$set(base.dir = "analysis/rmd/")
knitr::opts_chunk$set(
  fig.retina = 3, 
  fig.align = "center",
  out.width = "100%",
  echo = FALSE,
  fig.path="../../../analysis/paper/submission/3/appendices/"
)

loadd(bm_sp_sp_diplodia, bm_sp_nsp_diplodia,
      bm_nsp_nsp_diplodia)
```

# Resampling strategies {.tabset .tabset-fade}

## Spatial/Spatial

```{r}
tuning_effects_diplodia_sp_sp <- vis_tuning_effects(bm_sp_sp_diplodia$results$diplodia[2:5],
                                                    model_name = c(
                                                      "KNN",
                                                      "RF",
                                                      "SVM",
                                                      "BRT"
                                                    ),
                                                    resampling = "Spatial/Spatial",
                                                    hyperparameter = list(
                                                      c("k", "distance"),
                                                      c("min.node.size", "mtry"),
                                                      c("cost", "gamma"),
                                                      c("n.trees", "shrinkage")
                                                    ),
                                                    xlim = list(
                                                      c(1, 100),
                                                      c(1, 10),
                                                      c(-5, 12),
                                                      c(100, 10000)
                                                    ),
                                                    ylim = list(
                                                      c(1, 100),
                                                      c(1, 11),
                                                      c(-12, 3),
                                                      c(0, 0.2)
                                                    ),
                                                    default = list(
                                                      c(7, 2),
                                                      c(1, 3),
                                                      c(1, 1),
                                                      c(100, 0.001)
                                                    )
)
```

### KKNN

```{r tuning-effects-knn-sp-sp, dev = c("png")}
tuning_effects_diplodia_sp_sp[[1]]
```

### RF 

```{r tuning-effects-rf-sp-sp, dev = c("png")}
tuning_effects_diplodia_sp_sp[[2]]
```

### SVM 

```{r tuning-effects-svm-sp-sp, dev = c("png")}
tuning_effects_diplodia_sp_sp[[3]]
```

### BRT 

```{r tuning-effects-brt-sp-sp, dev = c("png")}
tuning_effects_diplodia_sp_sp[[4]]
```

## Spatial/Non-Spatial

```{r}
tuning_effects_diplodia_sp_nsp <- vis_tuning_effects(bm_sp_nsp_diplodia$results$diplodia[2:5],
                                                     model_name = c(
                                                       "KNN",
                                                       "RF",
                                                       "SVM",
                                                       "BRT"
                                                     ),
                                                     resampling = "Spatial/Non-Spatial",
                                                     hyperparameter = list(
                                                       c("k", "distance"),
                                                       c("min.node.size", "mtry"),
                                                       c("cost", "gamma"),
                                                       c("n.trees", "shrinkage")
                                                     ),
                                                     xlim = list(
                                                       c(1, 100),
                                                       c(1, 10),
                                                       c(-5, 12),
                                                       c(100, 10000)
                                                     ),
                                                     ylim = list(
                                                       c(1, 100),
                                                       c(1, 11),
                                                       c(-12, 3),
                                                       c(0, 0.2)
                                                     ),
                                                     default = list(
                                                       c(7, 2),
                                                       c(1, 3),
                                                       c(1, 1),
                                                       c(100, 0.001)
                                                     )
)
```

### KKNN

```{r tuning-effects-knn-sp-nsp, dev = c("png")}
tuning_effects_diplodia_sp_nsp[[1]]
```

### RF 

```{r tuning-effects-rf-sp-nsp, dev = c("png")}
tuning_effects_diplodia_sp_nsp[[2]]
```

### SVM 

```{r tuning-effects-svm-sp-nsp, dev = c("png")}
tuning_effects_diplodia_sp_nsp[[3]]
```

### BRT 

```{r tuning-effects-brt-sp-nsp, dev = c("png")}
tuning_effects_diplodia_sp_nsp[[4]]
```

## Non-Spatial/Non-Spatial

```{r}
loadd(bm_nsp_nsp_diplodia)

tuning_effects_diplodia_nsp_nsp <- vis_tuning_effects(bm_nsp_nsp_diplodia$results$diplodia[2:5],
                                                      model_name = c(
                                                        "KNN",
                                                        "RF",
                                                        "SVM",
                                                        "BRT"
                                                      ),
                                                      resampling = "Non-Spatial/Non-Spatial",
                                                      hyperparameter = list(
                                                        c("k", "distance"),
                                                        c("min.node.size", "mtry"),
                                                        c("cost", "gamma"),
                                                        c("n.trees", "shrinkage")
                                                      ),
                                                      xlim = list(
                                                        c(1, 100),
                                                        c(1, 10),
                                                        c(-5, 12),
                                                        c(100, 10000)
                                                      ),
                                                      ylim = list(
                                                        c(1, 100),
                                                        c(1, 11),
                                                        c(-12, 3),
                                                        c(0, 0.2)
                                                      ),
                                                      default = list(
                                                        c(7, 2),
                                                        c(1, 3),
                                                        c(1, 1),
                                                        c(100, 0.001)
                                                      )
)
```

### KKNN

```{r tuning-effects-knn-nsp-nsp, dev = c("png")}
tuning_effects_diplodia_nsp_nsp[[1]]
```

### RF 

```{r tuning-effects-rf-nsp-nsp, dev = c("png")}
tuning_effects_diplodia_nsp_nsp[[2]]
```

### SVM 

```{r tuning-effects-svm-nsp-nsp, dev = c("png")}
tuning_effects_diplodia_nsp_nsp[[3]]
```

### BRT 

```{r tuning-effects-brt-nsp-nsp, dev = c("png")}
tuning_effects_diplodia_nsp_nsp[[4]]
```

# Grid of most settings

```{r tuning_effects_all_models_mbo, fig.width=15, fig.path="../../../analysis/paper/submission/3/latex-source-files/", dev = c("png", "pdf")}
plot_grid(tuning_effects_diplodia_nsp_nsp[[4]], tuning_effects_diplodia_nsp_nsp[[2]],
          tuning_effects_diplodia_nsp_nsp[[3]], tuning_effects_diplodia_nsp_nsp[[1]],
          
          tuning_effects_diplodia_sp_nsp[[4]], tuning_effects_diplodia_sp_nsp[[2]],
          tuning_effects_diplodia_sp_nsp[[3]], tuning_effects_diplodia_sp_nsp[[1]],
          
          tuning_effects_diplodia_sp_sp[[4]], tuning_effects_diplodia_sp_sp[[2]],
          tuning_effects_diplodia_sp_sp[[3]], tuning_effects_diplodia_sp_sp[[1]],
          ncol = 4, nrow = 3
)
```
